# Generated by Django 6.0 on 2025-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_choice_votes_count_remove_room_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
