# Generated by Django 6.0 on 2025-12-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_banned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='banned_users',
        ),
        migrations.CreateModel(
            name='RoomBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_identifier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'banned_identifier')},
            },
        ),
    ]
